apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-otiohome-exporter.fullname" . }}
  labels:
    {{- include "prometheus-otiohome-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus-otiohome-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-otiohome-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prometheus-otiohome-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      env:
        - name: OTIO_ACCESS_TOKEN
          value: "{{ .Values.otio.auth.access_token }}"
        - name: OTIO_REFRESH_TOKEN
          value: "{{ .Values.otio.auth.refresh_token }}"
        - name: OTIO_PLACE_ID
          value: "{{ .Values.otio.profile.place_id }}"
        - name: OTIO_HOST
          value: "{{ .Values.otio.host }}"
        - name: OTIO_CLIENT_ID
          value: "{{ .Values.otio.auth.client_id }}"
        - name: OTIO_OPENID_HOST
          value: "{{ .Values.otio.auth.host }}"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OTIO_ACCESS_TOKEN
              value: "{{ .Values.otio.auth.access_token }}"
            - name: OTIO_REFRESH_TOKEN
              value: "{{ .Values.otio.auth.refresh_token }}"
            - name: OTIO_PLACE_ID
              value: "{{ .Values.otio.profile.place_id }}"
            - name: OTIO_HOST
              value: "{{ .Values.otio.host }}"
            - name: OTIO_CLIENT_ID
              value: "{{ .Values.otio.auth.client_id }}"
            - name: OTIO_OPENID_HOST
              value: "{{ .Values.otio.auth.host }}"
          ports:
            - name: http
              containerPort: 9100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
